l=[1,2,3,4,5,6,7]
# it=l.__iter__() 
it=iter(l)
print(it)
# print(it.__next__())
# print(it.__next__())
# print(it.__next__())
# print(it.__next__())
# print(it.__next__())
# print(it.__next__())
# print(it.__next__())
# print(it.__next__())
print(next(it))
print(next(it))
print(next(it))
print(next(it))
print(next(it))
